#+STARTUP: overview
#+PROPERTY: header-args :tangle init.el

* Early init
** Startup tweaks
   Make startup faster by reducing the frequency of garbage collection.

   #+BEGIN_SRC emacs-lisp :tangle early-init.el
     (setq gc-cons-threshold most-positive-fixnum
           gc-cons-percentage 0.6)
   #+END_SRC

   After Emacs startup has been completed, set `gc-cons-threshold' to
   16 MB and reset `gc-cons-percentage' to its original value.

   #+BEGIN_SRC emacs-lisp :tangle early-init.el
     (add-hook 'emacs-startup-hook
               #'(lambda ()
                   (setq gc-cons-threshold (* 16 1024 1024)
                         gc-cons-percentage 0.1)))
   #+END_SRC

   Increase the amount of data which Emacs reads from a sub-process
   in one read operation.
   The default 4096 bytes can be to low for i.e. lsp-mode.

   #+begin_src emacs-lisp :tangle early-init.el
     (setq read-process-output-max (* 1024 1024))
   #+end_src
** Disable menubar, toolbar, scrollbars and tooltips
   #+BEGIN_SRC emacs-lisp :tangle early-init.el
     (dolist (mode
              '(menu-bar-mode
                tool-bar-mode
                scroll-bar-mode
                tooltip-mode))
       (when (fboundp mode)
         (funcall mode -1)))
   #+END_SRC
** Start the initial frame maximized.
   #+BEGIN_SRC emacs-lisp :tangle early-init.el
     (setq default-frame-alist
           '((fullscreen . maximized)
             (vertical-scroll-bars . nil)
             (horizontal-scroll-bars . nil)))

   #+END_SRC
** Don't show startup screen on Emacs start
   #+BEGIN_SRC emacs-lisp :tangle early-init.el
     (setq-default inhibit-startup-screen t)
   #+END_SRC
** Disable bell
   #+BEGIN_SRC emacs-lisp :tangle early-init.el
     (setq ring-bell-function 'ignore)
   #+END_SRC
** Set theme
   #+BEGIN_SRC emacs-lisp :tangle early-init.el
     (load-theme 'modus-operandi t)
   #+END_SRC
* Package management
  Add melpo to the list of package archives.

  #+BEGIN_SRC emacs-lisp
    (require 'package)
    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
    (package-initialize)
  #+END_SRC
* Defaults
** Set font
   #+BEGIN_SRC emacs-lisp
     (set-frame-font "Monaco 12" nil t)
   #+END_SRC
** Editing
*** Highlight the current line
    #+BEGIN_SRC emacs-lisp
      ;; Enable it for all programming major modes
      (add-hook 'prog-mode-hook #'hl-line-mode)
      ;; and for all modes derived from text-mode
      (add-hook 'text-mode-hook #'hl-line-mode)
    #+END_SRC
*** Remove trailing whitespace on save
    #+BEGIN_SRC emacs-lisp
      (add-hook 'before-save-hook 'delete-trailing-whitespace)
    #+END_SRC
*** Auto close bracket insertion
    #+BEGIN_SRC emacs-lisp
      (electric-pair-mode 1)
    #+END_SRC
*** Show corresponding paren
    #+BEGIN_SRC emacs-lisp
      (show-paren-mode 1)
    #+END_SRC
*** Require a newline at the end of the file
    #+BEGIN_SRC emacs-lisp
      (defvar require-final-newline t)
    #+END_SRC
*** Set indentation to always use spaces
   #+BEGIN_SRC emacs-lisp
     (setq-default indent-tabs-mode nil)
   #+END_SRC
*** Comments
    Remap 'comment-line key to 'C-x C-\' because the
    default 'C-;' is not recognized by some terminals.

    #+BEGIN_SRC emacs-lisp
      (global-unset-key (kbd "C-x C-;"))
      (global-set-key (kbd "C-x C-\\") 'comment-line)
    #+END_SRC
** Scrolling
   #+BEGIN_SRC emacs-lisp
     (setq scroll-margin                   0  ;; Default
           scroll-step                     1
           scroll-conservatively           10000
           scroll-preserve-screen-position 1)
   #+END_SRC
** Tramp
   Set remote password prompts.

   #+BEGIN_SRC emacs-lisp
     (customize-set-variable
      'tramp-password-prompt-regexp
      (concat
       "^.*"
       (regexp-opt
        '("passphrase"
          "Passphrase"
          "password"
          "Password"
          ;; Google Authenticator
          "Verification code")
        t)
       ".*:\0? *"))
   #+END_SRC
** Tweaks
*** Add interactive command to open this file
    #+BEGIN_SRC emacs-lisp
      (global-set-key
       (kbd "C-c s")
       (lambda ()
         (interactive)
         (find-file-other-window (locate-user-emacs-file "readme.org"))))
    #+END_SRC
*** Autorefresh buffers on file change
    #+BEGIN_SRC emacs-lisp
      (global-auto-revert-mode t)
    #+END_SRC
*** Enable y/n answers
    #+BEGIN_SRC emacs-lisp
      (fset 'yes-or-no-p 'y-or-n-p)
    #+END_SRC
*** Remember cursor position
    #+BEGIN_SRC emacs-lisp
      (save-place-mode 1)
    #+END_SRC
*** Replace *Buffer List* with *Ibuffer*
    #+BEGIN_SRC emacs-lisp
      (global-set-key (kbd "C-x C-b") 'ibuffer)
    #+END_SRC
*** Switching between windows
    Bind the keyboard shortcut 'M-o' to the `other-window` function for easier
    switching between windows.

    #+begin_src emacs-lisp
      (global-set-key (kbd "M-o") 'other-window)
    #+end_src
    Enable windmove default keybindings so you can use the 'M-<arrow>' keyboard
    shortcuts to switch between windows.

    #+begin_src emacs-lisp
      (windmove-default-keybindings)
    #+end_src
*** Enable which-key
    Display the key bindings following your currently entered incomplete
    command (a prefix) in a popup.

    #+begin_src emacs-lisp
      (which-key-mode)
    #+end_src
** Backups
   Store all backup and autosave files in the 'backups' dir.

   #+BEGIN_SRC emacs-lisp
     (setq auto-save-list-file-prefix nil)
     (setq backup-directory-alist
           `(("." . ,(concat user-emacs-directory "backups"))))
   #+END_SRC
   Use version contral and keep multiple backup files.

   #+BEGIN_SRC emacs-lisp
     (setq backup-by-copying t
           delete-old-versions t
           kept-new-versions 10
           kept-old-versions 0
           version-control t
           vc-make-backup-files t)
   #+END_SRC
** Customize
   Move lines added by the customize system to a seperate file.
   Config changes made through the customize UI will be stored here.

   #+BEGIN_SRC emacs-lisp
     (setq custom-file (locate-user-emacs-file "custom.el"))

     (when (file-exists-p custom-file)
       (load custom-file))
   #+END_SRC
* Packages
** Company
   #+BEGIN_SRC emacs-lisp
     (use-package company
       :ensure t

       :hook (after-init . global-company-mode))
   #+END_SRC
** Decode JWT
   Decode the headers and payload of a JWT token.

   #+begin_src emacs-lisp
     (use-package jwt-content
       :vc (:url "https://github.com/igroen/jwt-content.el"
            :rev :newest))
   #+end_src
** Dired
   #+BEGIN_SRC emacs-lisp
     (use-package dired
       :config
       ;; Use dired-x to enable C-x C-j (dired-jump) and other features
       (use-package dired-x)

       ;; Omit files starting with a dot
       (setq dired-omit-files (concat dired-omit-files "\\|^\\..+$"))

       ;; Default omit files
       (setq-default dired-omit-mode t)

       ;; Make dired open in the same window when using RET or ^
       (define-key dired-mode-map (kbd "RET") 'dired-find-alternate-file)
       (define-key dired-mode-map (kbd "^")
         (lambda () (interactive) (find-alternate-file "..")))
       (put 'dired-find-alternate-file 'disabled nil))
   #+END_SRC
** Drag stuff
   #+BEGIN_SRC emacs-lisp
     (use-package drag-stuff
       :ensure t

       :bind (("M-p" . drag-stuff-up)
              ("M-n" . drag-stuff-down))

       :config (drag-stuff-global-mode 1))
   #+END_SRC
** Eldoc
   #+begin_src emacs-lisp
     (use-package eldoc)
   #+end_src
** Exec path from shell
   Make *GUI Emacs* use the proper $PATH and avoid a [[http://www.flycheck.org/en/latest/user/troubleshooting.html#flycheck-cant-find-any-programs-in-gui-emacs-on-macos][common setup issue on MacOS]].
   Without this package packages such as flycheck and EPA are not working correctly.

   #+BEGIN_SRC emacs-lisp
     (use-package exec-path-from-shell
       :ensure t

       :config
       (when (memq window-system '(mac ns x))
         (exec-path-from-shell-initialize)))
   #+END_SRC
** Expand region
   #+BEGIN_SRC emacs-lisp
     (use-package expand-region
       :ensure t

       :bind ("C-x w" . er/expand-region))
   #+END_SRC
** Flycheck
   #+BEGIN_SRC emacs-lisp
     (use-package flycheck
       :ensure t

       :hook (after-init . global-flycheck-mode))
   #+END_SRC
** Git
   #+BEGIN_SRC emacs-lisp
     (use-package magit
       :ensure t

       :bind ("C-x g" . magit-status)

       :hook (after-save-hook . magit-after-save-refresh-status))

     (use-package git-timemachine
       :ensure t
       :defer t)

     (use-package diff-hl
       :ensure t

       :hook ((magit-post-refresh . diff-hl-magit-post-refresh)
              (dired-mode . diff-hl-dired-mode-unless-remote))

       :init
       (global-diff-hl-mode)

       :config
       (diff-hl-margin-mode)
       (diff-hl-flydiff-mode))
   #+END_SRC
** GnuPG
   #+BEGIN_SRC emacs-lisp
     (use-package epa
       :config
       ;; Prefer armored ASCII (.asc)
       (setq epa-armor t)

       ;; Open .asc files in the same way as .gpg files
       (setq epa-file-name-regexp "\\.\\(gpg\\|asc\\)$")
       (epa-file-name-regexp-update)

       ;; Prompt for the password in the minibuffer
       (setq epg-pinentry-mode 'loopback))
   #+END_SRC
** Hydra
   #+begin_src emacs-lisp
     (use-package hydra
       :ensure t)
   #+end_src
** Ivy/Counsel/Swiper
*** Ivy
    Completion framework.

    #+BEGIN_SRC emacs-lisp
      (use-package ivy
        :ensure t

        :demand t

        :bind ("<f6>" . ivy-resume)

        :config
        (setq ivy-count-format "%d/%d "
              ivy-use-selectable-prompt t
              ivy-use-virtual-buffers t)
        (ivy-mode 1))
    #+END_SRC
*** Ivy-xref
    Select from xref candidates with ivy.

    #+BEGIN_SRC emacs-lisp
      (use-package ivy-xref
        :ensure t

        :init
        (setq xref-show-definitions-function #'ivy-xref-show-defs)
        (setq xref-show-xrefs-function #'ivy-xref-show-xrefs))
   #+END_SRC
*** Counsel
    Provides some useful commands for ivy.

    #+BEGIN_SRC emacs-lisp
      (use-package counsel
        :ensure t

        :bind
        ("M-x" . counsel-M-x)
        ("C-x C-f" . counsel-find-file)
        ("M-y" . counsel-yank-pop))
    #+END_SRC
*** Swiper
    Search through the current buffer.

    #+BEGIN_SRC emacs-lisp
      (use-package swiper
        :ensure t

        :bind
        ([remap isearch-forward]  . swiper)
        ([remap isearch-backward] . swiper))
    #+END_SRC
*** Flx
    Better fuzzy matching.

    #+BEGIN_SRC emacs-lisp
      (use-package flx
        :ensure t)
    #+END_SRC
*** Smex
    Show recently and most frequently used commands.

    #+BEGIN_SRC emacs-lisp
      (use-package smex
        :ensure t)
    #+END_SRC
*** Wgrep
    Edit a grep buffer and apply those changes to the file buffer.

    #+BEGIN_SRC emacs-lisp
      (use-package wgrep
        :ensure t)
    #+END_SRC
** Mood line
   #+BEGIN_SRC emacs-lisp
     (use-package mood-line
       :ensure t

       :config
       (mood-line-mode)

       :custom
       (mood-line-glyph-alist mood-line-glyphs-fira-code))
   #+END_SRC
** Multiple cursors
   #+BEGIN_SRC emacs-lisp
    (use-package multiple-cursors
      :ensure t

      :bind (("C-x C-m C-e" . mc/edit-lines)
             ("C-x C-m C-n" . mc/mark-next-like-this)
             ("C-x C-m C-p" . mc/mark-previous-like-this)
             ("C-x C-m C-a" . mc/mark-all-like-this)))
   #+END_SRC
** Org mode
   #+BEGIN_SRC emacs-lisp
     (use-package org
       :defer t
       :config
       (setq org-babel-python-command "python3")
       ;; Add languages for `SRC` code blocks in org-mode
       (org-babel-do-load-languages
        'org-babel-load-languages
        '((emacs-lisp . t)
          (shell . t)
          (python . t))))
   #+END_SRC
** Projectile
   #+BEGIN_SRC emacs-lisp
     (use-package projectile
       :ensure t

       :bind-keymap ("C-c p" . projectile-command-map)

       :config
       (setq projectile-enable-caching t)
       (projectile-mode))

     (use-package counsel-projectile
       :ensure t

       :config
       ;; The next line can be removed once
       ;; https://github.com/ericdanan/counsel-projectile/issues/189
       ;; is resolved.
       (projectile-known-projects)
       (counsel-projectile-mode))
   #+END_SRC
** Treemacs
*** treemacs
    #+BEGIN_SRC emacs-lisp
      (use-package treemacs
        :ensure t

        :bind (("M-0"       . treemacs-select-window)
               ("C-x t 1"   . treemacs-delete-other-windows)
               ("C-x t t"   . treemacs)
               ("C-x t B"   . treemacs-bookmark)
               ("C-x t C-t" . treemacs-find-file)
               ("C-x t M-t" . treemacs-find-tag))

        :config
        (treemacs-git-mode 'simple)

        (defun treemacs-python-ignore (filename absolute-path)
          (or (seq-contains-p
               '(".tox"
                 "__pycache__"
                 "build"
                 "dist"
                 "venv")
               filename)
              (string-match "^.+\\.egg-info$" filename)
              (string-match "^.+\\.pyc$" filename)))

        (add-to-list
         'treemacs-ignored-file-predicates #'treemacs-python-ignore))
    #+END_SRC
*** treemacs-projectile
    #+begin_src emacs-lisp
      (use-package treemacs-projectile
        :ensure t

        :after (treemacs projectile))
    #+end_src
*** treemacs-icons-dired
    #+begin_src emacs-lisp
      (use-package treemacs-icons-dired
        :ensure t

        ;; :after (treemacs dired)

        :hook (dired-mode . treemacs-icons-dired-enable-once))
    #+end_src
*** treemacs-magit
    #+begin_src emacs-lisp
      (use-package treemacs-magit
        :ensure t

        :after (treemacs magit))
    #+end_src
** VTerm
*** vterm
    #+BEGIN_SRC emacs-lisp
      (use-package vterm
        :ensure t

        :init
        (setq vterm-always-compile-module t)

        :config
        (setq vterm-kill-buffer-on-exit t)
        (setq vterm-toggle-reset-window-configration-after-exit t)
        (setq vterm-clear-scrollback-when-clearing t))
    #+END_SRC
*** vterm-toggle
    #+BEGIN_SRC emacs-lisp
      (use-package vterm-toggle
        :ensure t

        :bind (("C-c , RET" . vterm)
               ("C-c , /" . vterm-toggle)
               ("C-c , p" . vterm-toggle-forward)
               ("C-c , n" . vterm-toggle-backward)
               ("C-c , ." . vterm-toggle-insert-cd)))
    #+END_SRC
** XClip
   Enable xclip-mode to use the system clipboard when killing/yanking.
   Install xclip on Linux for this to work. On OSX pbcopy/pbpaste will be used.

   #+BEGIN_SRC emacs-lisp
     (use-package xclip
       :ensure t

       :config (xclip-mode t))
   #+END_SRC
** YAML
   #+BEGIN_SRC emacs-lisp
     (use-package yaml-mode
       :ensure t)
   #+END_SRC
* Programming
** LSP
   Enable Language Server Protocol support.

   #+begin_src emacs-lisp
     (use-package lsp-mode
       :ensure t

       :hook ((c-mode . lsp)
              (c++-mode . lsp)
              (python-mode . lsp)
              (lsp-mode . lsp-enable-which-key-integration))

       :commands lsp

       :init
       ;; Use plists for better performance.
       ;; https://emacs-lsp.github.io/lsp-mode/page/performance/#use-plists-for-deserialization
       (setenv "LSP_USE_PLISTS" "true")
       (setq lsp-keymap-prefix "C-c l")

       :config
       ;; Use flake8 instead of pycodestyle/pydocstyle/pyflakes
       (setq lsp-pylsp-plugins-pycodestyle-enabled nil)
       (setq lsp-pylsp-plugins-pydocstyle-enabled nil)
       (setq lsp-pylsp-plugins-pyflakes-enabled nil)
       (setq lsp-pylsp-plugins-flake8-enabled t)
       ;; Enable YAPF for code formatting
       (setq lsp-pylsp-plugins-yapf-enabled t)
       ;; Disable YASnippet
       (setq lsp-enable-snippet nil))
    #+end_src
** C++
*** Indentation
    Set indentation to 4 spaces

    #+BEGIN_SRC emacs-lisp
      (setq-default c-basic-offset 4)
    #+END_SRC
** Python
*** pyvenv
    #+begin_src emacs-lisp
      (use-package pyvenv
        :ensure t

        :defer t

        :config
        (pyvenv-mode t))
    #+end_src
* Snippets
** Delete current file and buffer
   #+BEGIN_SRC emacs-lisp
     (defun delete-current-file-copy-to-kill-ring ()
       "Delete current buffer/file and close the buffer, push content to `kill-ring'."
       (interactive)
       (progn
         (kill-new (buffer-string))
         (message "Buffer content copied to kill-ring.")
         (when (buffer-file-name)
           (when (file-exists-p (buffer-file-name))
             (progn
               (delete-file (buffer-file-name))
               (message "Deleted file: 「%s」." (buffer-file-name)))))
         (let ((buffer-offer-save nil))
           (set-buffer-modified-p nil)
           (kill-buffer (current-buffer)))))

     (global-set-key (kbd "C-c k")  'delete-current-file-copy-to-kill-ring)
   #+END_SRC
** Duplicate current line
   #+begin_src emacs-lisp
     (defun duplicate-line ()
        (interactive)
        (let ((col (current-column)))
          (move-beginning-of-line 1)
          (kill-line)
          (yank)
          (newline)
          (yank)
          (move-to-column col)))

      (global-set-key (kbd "C-c d") 'duplicate-line)
   #+end_src
** Smarter move to beginning of line
   Move point back to indentation of beginning of line.

   Move point to the first non-whitespace character on this line.
   If point is already there, move to the beginning of the line.
   Effectively toggle between the first non-whitespace character and
   the beginning of the line.

   If ARG is not nil or 1, move forward ARG - 1 lines first.  If
   point reaches the beginning or end of the buffer, stop there.
   #+BEGIN_SRC emacs-lisp
     (defun smarter-move-beginning-of-line (arg)
       (interactive "^p")
       (setq arg (or arg 1))

       (when (/= arg 1)
         (let ((line-move-visual nil))
           (forward-line (1- arg))))

       (let ((orig-point (point)))
         (back-to-indentation)
         (when (= orig-point (point))
           (move-beginning-of-line 1))))

     ;; remap C-a to `smarter-move-beginning-of-line'
     (global-set-key [remap move-beginning-of-line]
                     'smarter-move-beginning-of-line)
   #+END_SRC
* Tangle on save
  When opening this file for the first time the following warning is shown:
  "The local variables list in init.org contains values that may not be safe (*)".

  - Press 'y' to continue.
  - Next run `org-babel-tangle` (C-c C-v t) to generate an early-init.el and
    init.el file.
  - Restart emacs or load the generated files.
  - The next time this warning is shown press '!' to prevent future warnings.

  #+BEGIN_SRC emacs-lisp :tangle no
    ;; Local Variables:
    ;; eval: (add-hook 'after-save-hook (lambda () (org-babel-tangle)) nil t)
    ;; End:
  #+END_SRC
